#!/usr/bin/env node
// Turns a GPX track (the format most race organizers and trail sites
// publish courses in) into a `trails` + `trail_points` seed SQL script,
// matching the hand-curated shape already used for the Rim to Rim trail:
// a handful of landmark points with cumulative distance, not a dense GPS
// trace. RLS only allows the service role to write trails/trail_points
// (see supabase/migrations/20260825034028_initial_schema.sql), so this
// only *generates* SQL -- apply it with whatever admin access you have,
// e.g. the Supabase CLI (after `npx supabase login`):
//
//   node scripts/import-gpx.mjs --file course.gpx --name "Boston Marathon" \
//     --description "..." [--points 40] [--landmarks landmarks.json] [--out out.sql]
//   npx supabase db query --linked "$(cat out.sql)"
//
// landmarks.json (optional): [{ "mile": 5, "label": "Ashland" }, ...]
// -- each is snapped to the nearest kept point after simplification.

import { readFileSync, writeFileSync } from 'node:fs';

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++;
      } else {
        args[key] = true;
      }
    }
  }
  return args;
}

function haversineMiles(lat1, lon1, lat2, lon2) {
  const R = 3958.8; // Earth radius in miles
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function parseGpxPoints(gpxText) {
  const points = [];
  const re = /<trkpt\s+lat="(-?\d+\.?\d*)"\s+lon="(-?\d+\.?\d*)"/g;
  let m;
  while ((m = re.exec(gpxText))) {
    points.push({ lat: parseFloat(m[1]), lon: parseFloat(m[2]) });
  }
  return points;
}

/** Greedily keeps a point once cumulative distance has advanced by (total / (targetCount-1)) since the last kept point. */
function simplifyByDistance(rawPoints, targetCount) {
  const withDist = [{ ...rawPoints[0], dist: 0 }];
  for (let i = 1; i < rawPoints.length; i++) {
    const prev = withDist[i - 1];
    const d = haversineMiles(prev.lat, prev.lon, rawPoints[i].lat, rawPoints[i].lon);
    withDist.push({ ...rawPoints[i], dist: prev.dist + d });
  }
  const total = withDist[withDist.length - 1].dist;
  const step = total / (targetCount - 1);

  const kept = [withDist[0]];
  let nextTarget = step;
  for (let i = 1; i < withDist.length; i++) {
    if (withDist[i].dist >= nextTarget) {
      kept.push(withDist[i]);
      nextTarget += step;
    }
  }
  const last = withDist[withDist.length - 1];
  if (kept[kept.length - 1] !== last) kept.push(last);
  return { points: kept, totalMiles: total };
}

function nearestLandmarkLabels(keptPoints, landmarks) {
  const labels = new Array(keptPoints.length).fill(null);
  for (const { mile, label } of landmarks ?? []) {
    let bestIdx = 0;
    let bestDiff = Infinity;
    keptPoints.forEach((p, idx) => {
      const diff = Math.abs(p.dist - mile);
      if (diff < bestDiff) {
        bestDiff = diff;
        bestIdx = idx;
      }
    });
    labels[bestIdx] = label;
  }
  return labels;
}

function sqlEscape(str) {
  return str.replace(/'/g, "''");
}

const args = parseArgs(process.argv.slice(2));
if (!args.file || !args.name) {
  console.error(
    'Usage: node scripts/import-gpx.mjs --file <course.gpx> --name "<Trail Name>" [--description "..."] [--points 40] [--landmarks landmarks.json] [--out out.sql]'
  );
  process.exit(1);
}

const gpxText = readFileSync(args.file, 'utf8');
const rawPoints = parseGpxPoints(gpxText);
if (rawPoints.length < 2) {
  console.error(`Found only ${rawPoints.length} track points in ${args.file} -- is this a valid GPX track?`);
  process.exit(1);
}

const targetCount = args.points ? parseInt(args.points, 10) : 40;
const { points, totalMiles } = simplifyByDistance(rawPoints, targetCount);

const landmarks = args.landmarks ? JSON.parse(readFileSync(args.landmarks, 'utf8')) : null;
const labels = nearestLandmarkLabels(points, landmarks);

const name = sqlEscape(args.name);
const description = args.description ? sqlEscape(args.description) : null;
const totalMilesRounded = totalMiles.toFixed(2);

const valuesRows = points
  .map((p, i) => {
    const label = labels[i] ? `'${sqlEscape(labels[i])}'` : 'NULL';
    return `  (${i + 1}, ${p.lat.toFixed(6)}, ${p.lon.toFixed(6)}, ${p.dist.toFixed(2)}, ${label})`;
  })
  .join(',\n');

const sql = `-- Generated by scripts/import-gpx.mjs from ${args.file}
-- ${points.length} points simplified from ${rawPoints.length} raw GPX trackpoints, ${totalMilesRounded} mi total.
WITH new_trail AS (
  INSERT INTO public.trails (name, total_distance_miles, description)
  VALUES ('${name}', ${totalMilesRounded}, ${description ? `'${description}'` : 'NULL'})
  RETURNING id
)
INSERT INTO public.trail_points (trail_id, sequence, latitude, longitude, cumulative_distance_miles, label)
SELECT id, seq, lat, lon, dist, label FROM new_trail, (VALUES
${valuesRows}
) AS pts(seq, lat, lon, dist, label);
`;

const outPath = args.out || args.file.replace(/\.gpx$/i, '.sql');
writeFileSync(outPath, sql, 'utf8');
console.log(`Wrote ${points.length} points (${totalMilesRounded} mi) to ${outPath}`);
console.log(`Apply with: npx supabase db query --linked "$(cat ${outPath})"`);
